## SOURCE CODE
Here is the code that creates and insert the data used in database table

``` SQL
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS items;

CREATE TABLE IF NOT EXISTS Customers (
    customer_id INT AUTO_INCREMENT,
    first_name VARCHAR(15) NOT NULL,
    second_name VARCHAR(15) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    CONSTRAINT PK_custno PRIMARY KEY (customer_id)
);


INSERT INTO customers (first_name, second_name, email)
VALUE 
( 'Terry', 'Decker', 'wburke@example.org'),
('Kenneth', 'Henry', 'ryanlloyd@example.org'),
('Monica', 'Cox', 'stacie42@example.org'),
('Cameron', 'Davis', 'allisonveronica@example.com'),
('Laura', 'Parks', 'william04@example.org'),
('Patricia', 'Davis', 'alexis59@example.org')
;



CREATE TABLE IF NOT EXISTS Orders (
	order_id INT AUTO_INCREMENT,
    order_date DATE NOT NULL,
    customer_id INT,
    item_id INT,
    CONSTRAINT PK_facno PRIMARY KEY (order_id)
);

INSERT INTO orders(order_date, customer_id, item_id)
VALUES
('1993-04-04', 1, 2),
('2019-07-12', 1, 3),
('2008-07-06', 4, 1),
('1996-04-05', 8, 5),
('1970-09-22', 7, 4),
('1987-09-05', 5, 3),
('1996-09-28', 3, 3)
;



CREATE TABLE IF NOT EXISTS items (
    item_id INT AUTO_INCREMENT,
    item_name VARCHAR(255),
    amount INT,
    CONSTRAINT PK_facno PRIMARY KEY (item_id)
);

INSERT INTO items(item_name, amount)
VALUES
('pen', 20),
('book', 260),
('phone', 400),
('fan', 230),
('cloth', 50),
('apple', 100)
;


```

# Understanding Joins In SQL


### What is join in database?
Join in SQL is basically the process of combining two or more related tables together. As you progress in SQL, joins are very important to master.

### Why is SQL join important in Relational Database Management System (RDBMS)?
From RDBMS, the word `relational` is the key and join operations are performed on RDBMS to fetch information/data from related table. When designing relational databases, it is important to reduce data duplications and maintain data integrity. Normalization helped to keep data integrity but normalized database is not human readable, data are separated into different tables. To make meaning out of the separates table is the ability to join and join correctly.

In this illustration, I will be using a store database as an example and I will also keep it very simple since the purpose is to understand how to join tables. I will use three tables a store database should have, we are:
* Customer table
* Order table
* Item table

![dummy Store database](join/dummy_database.png)

***Image:*** *`dummy Store database`*

### Types of SQL joins
* Inner join
* Left join
* Right join
* Outer join
* Cross join

## Type of joins

### Inner joins

![inner_join](join\inner_join.jpg)

The venn diagram above gave the simple explanation of inner join. For the illustration, I will join customer table and order tabel. To query inner join here, we need to know what connects the two table together, looking at the schema diagram, it is the `customer_id`. The inner join query here is
``` sql
SELECT 
	c.customer_id, c.first_name, o.order_id
FROM 
	customers c
INNER JOIN 
	orders o on c.customer_id = o.customer_id;
```

From the output below, it is clear the that query returns record that matches with the `customer_id` on the two tables.

![](join/inner_joined.png)

***Image***: *output data - inner join

*For more understanding, follow up [here]*



The data above shows data of all order record associated with customer_id in the customer table, so every order that is not made by virtual customer will not be shown

### Left Joins

![left join](join/left_join.jpg)

The venn diagram above has given of the sense of what left join should be like. What left join does is that it returns all data for the table to the left and join the second table where it matches the left table with the referencing key (here it is `o.custome_id`)
*For more understanding, follow up [here]*

![](join/left_joined.png)

***Image***: Output data - Left join

With the output it is obviouly clear that `customer_id 2 and 6` have not ordered anything from the store and that is why their data is not in the order table.


The data returns all the data in the customer table (the left) and all the data the match order_id referencing customer_id on the record table (right table)

### Right join

![right join](join/right_join.jpg)

This is very similer to left join but interchangeably. To get the same data fetched from the left join, we have to interchange the table i.e customer table for order table and vise versa

In these example, I will join the three tables together using INNER JOIN and RIGHT JOIN. Let say we want to know if the all items sold are ordered from our registered customers (customers in the customer table). In this kind of situation, we have to join the three table together since customer is not directly related to the item table.

Here is the query:
``` SQL
SELECT 
    c.customer_id,
    c.first_name,
    c.second_name,
    o.order_id AS order_by_cust,
    i.item_id AS all_order_item,
    i.amount
FROM
    customers c
INNER JOIN
    orders o ON c.customer_id = o.customer_id
RIGHT JOIN
    items i ON i.item_id = o.item_id
;
    
```

In the query, it is important to know how the code is been run. The first join the code executed was the `INNER JOIN` which returned the inner join output above (with order_id of 1, 2, 3, 6 and 7), it then joined the output data to the RIGHT table (the all record in items table) using order_id to get the matched data. The output showed that not item sold are sold to only registered customer



*For more understanding, follow up [here]*

![](join/right_joined.png)

***Image***: *Output data - right join*